#!/usr/bin/env python

import fileinput
from sys import stderr
from collections import Counter

lengths = list()
for line in fileinput.input():
    if line.startswith('*** Source: '):
        print(line[12:].strip(), file=stderr)
    else:
        lengths.append(len(line))
        
print(Counter(lengths).most_common())
    
